In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import seaborn as sns
import os # LITTLE THING TO CORRECT AT THE END IF WE HAVE ENOUGH TIME. OTHERWISE DELETE IT
import math #to apply absolute value
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

import warnings
warnings.filterwarnings('ignore')

In [2]:
# Basic functions:

def data_exp(): # first exploration
    print("The dataframe shape is", data.shape, ".")
    print(" ")
    print("The dataframe columns are:")
    print(data.columns)
    print(" ")
    print("The dataframe data types are:")
    print(data.dtypes)
    return data.sample(5)

def data_clean(): # to standarize column names
    data.columns = cc = [column.lower().replace(' ', '_') for column in data] # standarizing the columns
    print(data.columns)
    print()

## 01 - Problem (case study)

Goal: We want to find the next Mbappé

## 02 - Getting Data

In [3]:
data = pd.read_csv('fifa21_male2.csv')
data_exp()

The dataframe shape is (17125, 107) .

The dataframe columns are:
Index(['ID', 'Name', 'Age', 'OVA', 'Nationality', 'Club', 'BOV', 'BP',
       'Position', 'Player Photo',
       ...
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'GK', 'Gender'],
      dtype='object', length=107)

The dataframe data types are:
ID              int64
Name           object
Age             int64
OVA             int64
Nationality    object
                ...
CB             object
RCB            object
RB             object
GK             object
Gender         object
Length: 107, dtype: object

,ID,Name,Age,OVA,Nationality,Club,BOV,BP,Position,Player Photo,Club Logo,Flag Photo,POT,Team & Contract,Height,Weight,foot,Growth,Joined,Loan Date End,Value,Wage,Release Clause,Contract,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,RAM,LM,LCM,CM,RCM,RM,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,GK,Gender
3860,201505,David López,30,76,Spain,RCD Espanyol,77,CB,CDM CB,https://cdn.sofifa.com/players/201/505/20_120.png,https://cdn.sofifa.com/teams/452/light_60.png,https://cdn.sofifa.com/flags/es.png,76,RCD Espanyol 2016 ~ 2023,"6'0""",179lbs,Right,0,"Aug 26, 2016",NaN,€6.5M,€9K,€9.8M,2016 ~ 2023,317,55,53,75,78,56.0,303,64,48.0,46,70,75,279,54,54,47.0,72,52.0,353,77,73.0,63,80,60,336,78,80.0,59.0,69.0,50,69.0,229,75,79,75.0,54,9,12,7,11,15,1871,398,3 ★,2★,Medium,High,1 ★,54,60,67,65,77,75,19,66+2,66+2,66+2,63+0,66+0,66+0,66+0,63+0,67+2,67+2,67+2,65+2,71+2,71+2,71+2,65+2,70+2,75+1,75+1,75+1,70+2,71+2,77+-1,77+-1,77+-1,71+2,18+2,Male
3192,196848,I. Ávila,29,65,Peru,Melgar FBC,65,ST,ST,https://cdn.sofifa.com/players/196/848/20_120.png,https://cdn.sofifa.com/teams/111334/light_60.png,https://cdn.sofifa.com/flags/pe.png,65,Melgar FBC 2019 ~ 2021,"5'7""",154lbs,Right,0,"Jul 1, 2019",NaN,€550K,€500,€1.2M,2019 ~ 2021,290,36,72,65,57,60.0,283,62,56.0,56,46,63,368,67,65,76.0,71,89.0,303,64,58.0,56,60,65,254,50,33.0,64.0,37.0,70,60.0,80,41,19,20.0,60,12,13,8,13,14,1638,337,3 ★,3★,High,Low,1 ★,66,68,47,66,33,57,4,65+0,65+0,65+0,61+0,63+0,63+0,63+0,61+0,60+2,60+2,60+2,58+2,53+2,53+2,53+2,58+2,46+2,45+2,45+2,45+2,46+2,44+2,43+2,43+2,43+2,44+2,19+2,Male
4089,202864,N. Peñailillo,27,66,Chile,CD Antofagasta,66,LB,LB,https://cdn.sofifa.com/players/202/864/20_120.png,https://cdn.sofifa.com/teams/112533/light_60.png,https://cdn.sofifa.com/flags/cl.png,66,CD Antofagasta 2019 ~ 2023,"6'1""",165lbs,Left,0,"Jan 23, 2019",NaN,€575K,€1K,€776K,2019 ~ 2023,310,67,61,62,71,49.0,329,64,64.0,74,62,65,324,80,71,57.0,62,54.0,384,75,84.0,71,82,72,324,71,60.0,64.0,59.0,70,51.0,182,58,67,57.0,58,8,9,10,16,15,1911,408,2 ★,3★,High,Medium,1 ★,75,66,66,63,61,77,3,66+0,66+0,66+0,66+0,66+0,66+0,66+0,66+0,65+1,65+1,65+1,66+0,65+1,65+1,65+1,66+0,65+1,65+1,65+1,65+1,65+1,65+1,66+0,66+0,66+0,65+1,17+2,Male
8302,227832,E. Yao,23,65,Ivory Coast,FC Lugano,66,CB,CB RB,https://cdn.sofifa.com/players/227/832/20_120.png,https://cdn.sofifa.com/teams/10032/light_60.png,https://cdn.sofifa.com/flags/ci.png,72,FC Lugano 2017 ~ 2020,"6'0""",168lbs,Right,7,"Jul 21, 2017",NaN,€675K,€2K,€1.1M,2017 ~ 2020,205,38,23,61,53,30.0,221,53,38.0,36,38,56,303,67,70,61.0,58,47.0,305,48,85.0,67,75,30,243,68,65.0,30.0,36.0,44,64.0,186,57,66,63.0,52,7,10,16,9,10,1515,332,2 ★,2★,Medium,Medium,1 ★,69,31,43,55,62,72,4,47+2,47+2,47+2,48+0,47+0,47+0,47+0,48+0,47+2,47+2,47+2,49+2,49+2,49+2,49+2,49+2,59+2,58+2,58+2,58+2,59+2,60+2,64+2,64+2,64+2,60+2,15+2,Male
3978,202198,J. Slew,27,58,England,Morecambe,58,ST,ST LW LM,https://cdn.sofifa.com/players/202/198/20_120.png,https://cdn.sofifa.com/teams/357/light_60.png,https://cdn.sofifa.com/flags/gb-eng.png,58,Morecambe 2020 ~ 2021,"6'3""",179lbs,Right,0,"Jan 2, 2020",NaN,€140K,€2K,€245K,2020 ~ 2021,266,53,56,55,46,56.0,221,59,33.0,40,32,57,336,81,79,66.0,50,60.0,301,61,61.0,55,72,52,233,45,25.0,55.0,52.0,56,58.0,65,21,22,22.0,64,16,10,15,13,10,1486,329,3 ★,2★,Medium,Medium,1 ★,80,56,46,59,26,62,5,58+0,58+0,58+0,58+0,57+0,57+0,57+0,58+0,55+2,55+2,55+2,56+2,47+2,47+2,47+2,56+2,44+2,38+2,38+2,38+2,44+2,42+2,38+2,38+2,38+2,42+2,17+2,Male

This dataset has 17.125 player information in  unique data in 107 columns. 
* The features that might be useful for the purpose of our analysis are **example** like `Example1`, `Example2`, `Example3` and `Example4`.
* Also, since we want to know their **buying behavior** we will need data from numerical features such as `Example1`, `Example2` or `Example3`
* The target for our dataset will be `Value`.

## 03 - Cleaning/Wrangling

In [4]:
data_clean() # to standarize the column names

Index(['id', 'name', 'age', 'ova', 'nationality', 'club', 'bov', 'bp',
       'position', 'player_photo',
       ...
       'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk', 'gender'],
      dtype='object', length=107)

In [5]:
data = data.rename(columns={"team_&_contract": "team&contract"})

In [6]:
data_copy = data.copy() # as best practices, we make a copy of our data

In [7]:
# Check if "id" has duplicated values
if data_copy['id'].duplicated().any():
    print("There are duplicate values in 'id'.")
else:
    print("All values in 'id' are unique.")

All values in 'id' are unique.

In [8]:
data_headers = list(data.columns.values) # to get and check all column names
print("The Column Headers are :", data_headers)

# TO PUT THE TARGET AT THE END. LET'S DO IT LATER

The Column Headers are : ['id', 'name', 'age', 'ova', 'nationality', 'club', 'bov', 'bp', 'position', 'player_photo', 'club_logo', 'flag_photo', 'pot', 'team&contract', 'height', 'weight', 'foot', 'growth', 'joined', 'loan_date_end', 'value', 'wage', 'release_clause', 'contract', 'attacking', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'skill', 'dribbling', 'curve', 'fk_accuracy', 'long_passing', 'ball_control', 'movement', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'power', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'mentality', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure', 'defending', 'marking', 'standing_tackle', 'sliding_tackle', 'goalkeeping', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes', 'total_stats', 'base_stats', 'w/f', 'sm', 'a/w', 'd/w', 'ir', 'pac', 'sho', 'pas', 'dri', 'def', 'phy', 'hits', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk', 'gender']

### Dealing with Null values

In [9]:
# Check for empty cells in the entire DataFrame
null_cols = data_copy.isnull().sum()
null_cols = null_cols[null_cols > 0]
null_cols

club                 23
position            413
club_logo            23
joined               58
loan_date_end     16215
volleys              58
curve                58
agility              58
balance              58
jumping              58
interceptions         7
positioning           7
vision               58
composure           423
sliding_tackle       58
a/w                  89
d/w                  89
dtype: int64

In [10]:
# Get rid of loan_date_end since it has to many empty values
data_copy = data_copy.drop(columns=["loan_date_end"])

In [11]:
# Create a new dataset without the rows with empty cells in "value" column
# data2 = data.dropna(subset=['value'])
# data2

In [12]:
# function to convert value to unified format
def convert_value(value):
    if isinstance(value, float):
        return value
    elif value.endswith('K'):
        return float(value[1:-1]) * 1000
    elif value.endswith('M'):
        return float(value[1:-1]) * 1000000
    else:
        try:
            return float(value)
        except ValueError:
            return None

# apply function to value column
data_copy['value'] = data_copy['value'].apply(convert_value)

data.sample(2)

,id,name,age,ova,nationality,club,bov,bp,position,player_photo,club_logo,flag_photo,pot,team&contract,height,weight,foot,growth,joined,loan_date_end,value,wage,release_clause,contract,attacking,crossing,finishing,heading_accuracy,short_passing,volleys,skill,dribbling,curve,fk_accuracy,long_passing,ball_control,movement,acceleration,sprint_speed,agility,reactions,balance,power,shot_power,jumping,stamina,strength,long_shots,mentality,aggression,interceptions,positioning,vision,penalties,composure,defending,marking,standing_tackle,sliding_tackle,goalkeeping,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,total_stats,base_stats,w/f,sm,a/w,d/w,ir,pac,sho,pas,dri,def,phy,hits,ls,st,rs,lw,lf,cf,rf,rw,lam,cam,ram,lm,lcm,cm,rcm,rm,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,gender
13998,247448,G. Ranjitsingh,26,52,Trinidad &amp; Tobago,Minnesota United FC,52,GK,GK,https://cdn.sofifa.com/players/247/448/20_120.png,https://cdn.sofifa.com/teams/111138/light_60.png,https://cdn.sofifa.com/flags/tt.png,55,Minnesota United FC 2020 ~ 2020,"6'3""",194lbs,Right,3,"Jan 1, 2020",NaN,€45K,€950,€71K,2020 ~ 2020,66,12,8,10,28,8.0,84,13,13.0,11,28,19,143,24,17,39.0,39,24.0,162,38,40.0,18,59,7,77,23,11.0,7.0,24.0,12,29.0,32,9,13,10.0,261,53,52,50,46,60,825,281,1 ★,1★,Medium,Medium,1 ★,53,52,50,60,20,46,3,20+2,20+2,20+2,18+0,19+0,19+0,19+0,18+0,20+2,20+2,20+2,19+2,21+2,21+2,21+2,19+2,17+2,21+2,21+2,21+2,17+2,17+2,20+2,20+2,20+2,17+2,51+2,Male
15596,254252,M. Hany,24,70,Egypt,Egypt,70,RB,RB,https://cdn.sofifa.com/players/254/252/20_120.png,https://cdn.sofifa.com/teams/111130/light_60.png,https://cdn.sofifa.com/flags/eg.png,75,Egypt Free,"5'9""",159lbs,Right,5,"Jan 1, 2015",NaN,€0,€0,€0,Free,313,71,48,60,68,66.0,322,67,67.0,55,64,69,364,76,74,76.0,64,74.0,323,64,70.0,70,64,55,293,63,66.0,61.0,58.0,45,66.0,201,67,66,68.0,53,10,12,11,5,15,1869,395,3 ★,2★,Medium,Medium,1 ★,75,54,65,69,66,66,9,62+2,62+2,62+2,65+0,64+0,64+0,64+0,65+0,64+2,64+2,64+2,66+2,65+2,65+2,65+2,66+2,68+2,66+2,66+2,66+2,68+2,68+2,66+2,66+2,66+2,68+2,16+2,Male

In [13]:
# Check the data type of the 'value' column
data_copy['value'].dtype

dtype('float64')

In [14]:
# id is unique, so I passed it as the index
data_copy = data_copy.set_index('id')

In [15]:
data_copy.head()

,name,age,ova,nationality,club,bov,bp,position,player_photo,club_logo,flag_photo,pot,team&contract,height,weight,foot,growth,joined,value,wage,release_clause,contract,attacking,crossing,finishing,heading_accuracy,short_passing,volleys,skill,dribbling,curve,fk_accuracy,long_passing,ball_control,movement,acceleration,sprint_speed,agility,reactions,balance,power,shot_power,jumping,stamina,strength,long_shots,mentality,aggression,interceptions,positioning,vision,penalties,composure,defending,marking,standing_tackle,sliding_tackle,goalkeeping,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,total_stats,base_stats,w/f,sm,a/w,d/w,ir,pac,sho,pas,dri,def,phy,hits,ls,st,rs,lw,lf,cf,rf,rw,lam,cam,ram,lm,lcm,cm,rcm,rm,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,gender
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2,G. Pasquale,33,69,Italy,Udinese,71,LWB,LM,https://cdn.sofifa.com/players/000/002/16_120.png,https://cdn.sofifa.com/teams/55/light_60.png,https://cdn.sofifa.com/flags/it.png,69,Udinese 2008 ~ 2016,"6'0""",181lbs,Left,0,"Jul 1, 2008",625000.0,€7K,€0,2008 ~ 2016,313,75,50,59,71,58.0,338,73,65.0,60,69,71,347,68,74,68.0,69,68.0,347,74,68.0,69,68,68,320,72,69.0,63.0,66.0,50,NaN,208,70,69,69.0,56,14,5,15,10,12,1929,408,3 ★,2★,Medium,High,2 ★,71,59,70,71,68,69,4,65+0,65+0,65+0,68+0,67+0,67+0,67+0,68+0,68+0,68+0,68+0,69+0,69+0,69+0,69+0,69+0,71+-2,70+-1,70+-1,70+-1,71+-2,70+-1,69+0,69+0,69+0,70+-1,17+0,Male
16,Luis García,37,71,Spain,KAS Eupen,70,CM,CM CAM CDM,https://cdn.sofifa.com/players/000/016/19_120.png,https://cdn.sofifa.com/teams/2013/light_60.png,https://cdn.sofifa.com/flags/es.png,71,KAS Eupen 2014 ~ 2019,"5'10""",143lbs,Right,0,"Jul 19, 2014",600000.0,€7K,€1.1M,2014 ~ 2019,337,68,64,61,76,68.0,369,69,79.0,79,71,71,305,56,50,62.0,65,72.0,324,75,54.0,64,60,71,362,71,71.0,72.0,73.0,75,79.0,153,70,43,40.0,56,9,12,13,11,11,1906,385,4 ★,3★,Medium,Medium,1 ★,53,69,73,69,58,63,4,67+1,67+1,67+1,67+0,68+0,68+0,68+0,67+0,70+1,70+1,70+1,68+1,70+1,70+1,70+1,68+1,62+1,66+1,66+1,66+1,62+1,60+1,60+1,60+1,60+1,60+1,17+1,Male
27,J. Cole,33,71,England,Coventry City,71,CAM,CAM RM RW LM,https://cdn.sofifa.com/players/000/027/16_120.png,https://cdn.sofifa.com/teams/1800/light_60.png,https://cdn.sofifa.com/flags/gb-eng.png,71,Coventry City 2016 ~ 2020,"5'9""",161lbs,Right,0,"Jan 7, 2016",1100000.0,€15K,€0,2016 ~ 2020,337,80,64,41,77,75.0,387,79,84.0,77,69,78,295,48,42,71.0,59,75.0,284,72,58.0,29,56,69,317,69,39.0,69.0,74.0,66,NaN,99,35,34,30.0,51,9,6,13,16,7,1770,354,4 ★,4★,Medium,Low,2 ★,45,68,76,77,36,52,11,64+0,64+0,64+0,70+0,69+0,69+0,69+0,70+0,71+0,71+0,71+0,68+0,66+0,66+0,66+0,68+0,52+0,54+0,54+0,54+0,52+0,47+0,46+0,46+0,46+0,47+0,15+0,Male
36,D. Yorke,36,68,Trinidad &amp; Tobago,Sunderland,70,ST,NaN,https://cdn.sofifa.com/players/000/036/09_120.png,https://cdn.sofifa.com/teams/106/light_60.png,https://cdn.sofifa.com/flags/tt.png,82,Sunderland 2009,"5'11""",165lbs,Right,14,NaN,NaN,€0,€0,2009,264,54,70,60,80,NaN,255,68,NaN,46,64,77,176,59,62,NaN,55,NaN,239,63,NaN,51,66,59,271,59,70.0,72.0,NaN,70,NaN,75,34,41,NaN,68,5,21,64,21,21,1348,369,3 ★,1★,NaN,NaN,1 ★,61,66,66,69,47,60,3,67+0,67+0,67+0,66+0,67+0,67+0,67+0,66+0,70+0,70+0,70+0,66+0,68+0,68+0,68+0,66+0,56+0,65+0,65+0,65+0,56+0,57+0,51+0,51+0,51+0,57+0,22+0,Male
41,Iniesta,36,81,Spain,Vissel Kobe,82,CAM,CM CAM,https://cdn.sofifa.com/players/000/041/20_120.png,https://cdn.sofifa.com/teams/101146/light_60.png,https://cdn.sofifa.com/flags/es.png,81,Vissel Kobe 2018 ~ 2021,"5'7""",150lbs,Right,0,"Jul 16, 2018",5500000.0,€12K,€7.2M,2018 ~ 2021,367,75,69,54,90,79.0,408,85,80.0,70,83,90,346,61,56,79.0,75,75.0,297,67,40.0,58,62,70,370,58,70.0,78.0,93.0,71,89.0,181,68,57,56.0,45,6,13,6,13,7,2014,420,4 ★,4★,High,Medium,4 ★,58,70,85,85,63,59,149,72+3,72+3,72+3,79+0,79+0,79+0,79+0,79+0,82+-1,82+-1,82+-1,79+2,81+0,81+0,81+0,79+2,70+3,73+3,73+3,73+3,70+3,67+3,64+3,64+3,64+3,67+3,17+3,Male

In [16]:
# checking if column 'team&contract' can be dropped since info is in 'club' and 'contract'
selected_columns = data_copy.loc[:, ['club', 'team&contract', 'contract']]
selected_columns

                 club                    team&contract              contract
id
2             Udinese              Udinese 2008 ~ 2016           2008 ~ 2016
16          KAS Eupen            KAS Eupen 2014 ~ 2019           2014 ~ 2019
27      Coventry City        Coventry City 2016 ~ 2020           2016 ~ 2020
36         Sunderland                  Sunderland 2009                  2009
41        Vissel Kobe          Vissel Kobe 2018 ~ 2021           2018 ~ 2021
...               ...                              ...                   ...
259088     CD Tondela  CD Tondela Jun 30, 2021 On Loan  Jun 30, 2021 On Loan
259090        Burnley              Burnley 2020 ~ 2021           2020 ~ 2021
259091        Burnley              Burnley 2020 ~ 2022           2020 ~ 2022
259101  SK Sturm Graz        SK Sturm Graz 2020 ~ 2023           2020 ~ 2023
259105          Lecce                Lecce 2020 ~ 2024           2020 ~ 2024

[17125 rows x 3 columns]

In [17]:
# Get rid of several columns
data_copy = data_copy.drop(columns=["player_photo", "club_logo", "flag_photo", "team&contract", "gender"])

### Encoding

In [18]:
# Convert height data from feet and inches to centimeters

## LET'S CHECK IT GUYS IS IMPORTANT ##

data_copy['height_cm'] = data_copy['height'].apply(lambda x: int(x.split("'")[0])*30.48 + int(x.split("'")[1].replace('"', ''))*2.54)
data_copy['height_cm']

# Drop the original 'height' column
data_copy.drop('height', axis=1, inplace=True)

In [20]:
# Convert weight data from pounds to kilograms
data_copy['weight_kg'] = data_copy['weight'].apply(lambda x: int(x[:-3]) / 2.2046)
data_copy['weight_kg']

# Drop the original 'weight' column
data_copy.drop('weight', axis=1, inplace=True)

In [21]:
# Convert wage and release_clause data to numeric value
data_copy['wage'] = data_copy['wage'].apply(convert_value)
data_copy['release_clause'] = data_copy['release_clause'].apply(convert_value)
data_copy['wage']

id
2          7000.0
16         7000.0
27        15000.0
36            NaN
41        12000.0
           ...
259088     2000.0
259090     3000.0
259091     2000.0
259101     3000.0
259105     2000.0
Name: wage, Length: 17125, dtype: float64

In [22]:
data_copy['release_clause']

id
2               NaN
16        1100000.0
27              NaN
36              NaN
41        7200000.0
            ...
259088          NaN
259090     273000.0
259091     273000.0
259101     784000.0
259105     788000.0
Name: release_clause, Length: 17125, dtype: float64

In [23]:
# Apply lambda function to 'w/f' column
data_copy['w/f_encoded'] = data_copy['w/f'].apply(lambda x: int(x[0]))
data_copy['w/f_encoded']

id
2         3
16        4
27        4
36        3
41        4
         ..
259088    2
259090    3
259091    3
259101    4
259105    3
Name: w/f_encoded, Length: 17125, dtype: int64

In [24]:
# Drop the original 'w/f' column
data_copy.drop('w/f', axis=1, inplace=True)

## MAKE A FUNCTION TO DROP THE COLUMNS GUYS

In [25]:
# Apply lambda function to 'w/f' column
data_copy['sm_encoded'] = data_copy['sm'].apply(lambda x: int(x[0]))
data_copy['sm_encoded']

id
2         2
16        3
27        4
36        1
41        4
         ..
259088    2
259090    2
259091    2
259101    2
259105    3
Name: sm_encoded, Length: 17125, dtype: int64

In [27]:
# Drop the original 'sm' column
data_copy.drop('sm', axis=1, inplace=True)

In [28]:
# Apply lambda function to 'w/f' column
data_copy['ir_encoded'] = data_copy['ir'].apply(lambda x: int(x[0]))
data_copy['ir_encoded']

## DEFINE A FUNCTION FOR LAMBDA

id
2         2
16        1
27        2
36        1
41        4
         ..
259088    1
259090    1
259091    1
259101    1
259105    1
Name: ir_encoded, Length: 17125, dtype: int64

In [29]:
# Drop the original 'sm' column
data_copy.drop('ir', axis=1, inplace=True)

In [ ]:
## HUGO> to encode left and right

In [35]:
# Initialize the LabelEncoder object
le = LabelEncoder()

# Fit and transform the data frame column
data_copy['a/w_encoded'] = le.fit_transform(data_copy['a/w'])
data_copy['d/w_encoded'] = le.fit_transform(data_copy['d/w'])

# Drop the original 'a/w' and 'd/w' column
data_copy.drop('a/w', axis=1, inplace=True)
data_copy.drop('d/w', axis=1, inplace=True)

In [31]:
# Modify cells with 'K' character, leave others unchanged, turn it to integer
data_copy['hits'] = data_copy['hits'].apply(lambda x: float(x.replace('K','')) * 1000 if isinstance(x, str) and 'K' in x else x).astype(int)

In [32]:
data_copy['hits'].unique()

array([   4,   11,    3,  149,    7,    9,   16,   10,    5,    8,  154,
          6,   18,   22,   34,   19,   15,   14,   27,   21,  309,   32,
        151,  750,   13,   39,   83,   20,  442,   92,   23,   29,   30,
         12,   31,  297,   36,   90,   88,   24,  171,   40,   25,   60,
        103,   38,   82,   57,   17,   26,   44,   67,  571,   61,   68,
         37,  231,   58,   62,   28,   51,   45,   80,  162,   59,  138,
        220,   93,   47,  281,   33,   46,   35,  830,   43,   64,   49,
         48,   54,  259,  161,   74,  434,   42,  131,  222,  229,  125,
        142,   81,  128,   78,  109,   72,   75,  111,   63,  123,  136,
         89,   55,  663,   97,   41,  143,   73,  464,  232,  164,  212,
        129,   79,  107,   69,  117,   71,  101,  202,  140,  110,   66,
       6300,  122,   95,  189,  157,  215,   52,  248,  178,  238,  208,
        214,  407, 1200,  349,  180,  224,  155,  147,   98,   99,  152,
        148,  120,  167,  158,   70,  328,  183,   56,  141,  173,  132,
         87,   65,  313,  223,  487,  401,   96,  647,   76,  439,  177,
        112,  100,  303,   86,  134,  233,  347,  195,   85,  546,   53,
         91,  221,  213,  367,  166,  118,   50,  243,  406,  179,  153,
        363,  113,  174,  193,  446,  472,  364,  116,  160,  529,  217,
       4100,  292,   84,  176,  199,  197,  594,  508,  105,  511,  146,
        102,  362, 1900,  226,  156,  182,  270,  307,  196,  235,  310,
        119,  108,  420,  200,  211,  608,  341,  302,  413,  172,  204,
        321,  127,   77,  279,  181, 2300,  201,  135,  389,  249,  227,
        206,  284,  359,  163,  447,  115,  277,  219,  595,  477,  504,
        253,  170,  114,  165,  257,  417,  293,  324,  264,  274,  124,
        190,  391,  374,  186,  386,  256,  382,  515,  326,  553,  655,
        453,  175,  247,  478,  185,  192,  144,  104,  139,  433,  312,
        168,  334,  258,  488,  203,  188,  632,  261,  393,  509,  280,
        777, 1100,  228,  299,  344,  191,  241, 1000,  262,  216,  294,
        205,  282,  234,  298,  456,  342,  230, 1300,  240,  337,  210,
         94,  236,  377,  357,  338,  378,  395,  314,  405, 2900,  242,
        287,  278,  441,  187,  516,  431, 1600,  829,  169,  184,  661,
        465,  239,  130,  304,  296,  557,  133,  519,  250,  225,  106,
        569,  255,  271,  436,  365,  772,  137,  868,  290,  343,  479,
        662,  435,  332,  437,  412,  150,  273,  660,  491,  370,  565,
        305,  457,  252,  246,  354,  245,  322,  574,  300,  674,  598,
        455,  260,  350,  556,  316,  194,  353,  418,  679,  572,  410,
        730,  371,  358,  145,  770,  462,  751,  466,  672,  484,  330,
       1500,  468, 4900,  121,  823,  159, 1700,  198,  263,  600, 2000,
        315,  545,  266,  340,  555,  416,  301,  854,  524, 3600,  403,
        552,  295,  380,  743,  825,  520,  562,  311,  388,  209,  817,
        460,  448,  761,  345,  526,  579,  538,  887, 3800,  959,  498,
        360,  275,  396,  792,  366,  254,  858,  440,  764,  860,  573,
        604,  318,  361,  352,  535,  928,  268,  724,  683,  542,  265,
        306,  308,  430,  709,  383,  932,  390,  821,  402,  461,  583,
        601,  593, 3000,  722,  689, 2700,  715,  381, 5000,  771,  346,
        901, 2600, 2200,  335,  670,  812, 1400,  368, 2100,  974,  649,
        495,  776,  684,  957,  961,  850,  473,  748,  445,  611, 3300,
        289,  615, 2800,  596, 9200,  272,  934,  784, 1800,  738,  291,
        720])

In [33]:
# Create a new dataframe with only the numerical columns using select_dtypes
numericals = data_copy.select_dtypes(np.number).apply(lambda x: round(x,2))
numericals.head()

,age,ova,bov,pot,growth,value,wage,release_clause,attacking,crossing,finishing,heading_accuracy,short_passing,volleys,skill,dribbling,curve,fk_accuracy,long_passing,ball_control,movement,acceleration,sprint_speed,agility,reactions,balance,power,shot_power,jumping,stamina,strength,long_shots,mentality,aggression,interceptions,positioning,vision,penalties,composure,defending,marking,standing_tackle,sliding_tackle,goalkeeping,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,total_stats,base_stats,pac,sho,pas,dri,def,phy,hits,height_cm,weight_kg,w/f_encoded,sm_encoded,ir_encoded,a/w_encoded,d/w_encoded
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2,33,69,71,69,0,625000.0,7000.0,NaN,313,75,50,59,71,58.0,338,73,65.0,60,69,71,347,68,74,68.0,69,68.0,347,74,68.0,69,68,68,320,72,69.0,63.0,66.0,50,NaN,208,70,69,69.0,56,14,5,15,10,12,1929,408,71,59,70,71,68,69,4,182.88,82.10,3,2,2,2,0
16,37,71,70,71,0,600000.0,7000.0,1100000.0,337,68,64,61,76,68.0,369,69,79.0,79,71,71,305,56,50,62.0,65,72.0,324,75,54.0,64,60,71,362,71,71.0,72.0,73.0,75,79.0,153,70,43,40.0,56,9,12,13,11,11,1906,385,53,69,73,69,58,63,4,177.80,64.86,4,3,1,2,2
27,33,71,71,71,0,1100000.0,15000.0,NaN,337,80,64,41,77,75.0,387,79,84.0,77,69,78,295,48,42,71.0,59,75.0,284,72,58.0,29,56,69,317,69,39.0,69.0,74.0,66,NaN,99,35,34,30.0,51,9,6,13,16,7,1770,354,45,68,76,77,36,52,11,175.26,73.03,4,4,2,2,1
36,36,68,70,82,14,NaN,NaN,NaN,264,54,70,60,80,NaN,255,68,NaN,46,64,77,176,59,62,NaN,55,NaN,239,63,NaN,51,66,59,271,59,70.0,72.0,NaN,70,NaN,75,34,41,NaN,68,5,21,64,21,21,1348,369,61,66,66,69,47,60,3,180.34,74.84,3,1,1,3,3
41,36,81,82,81,0,5500000.0,12000.0,7200000.0,367,75,69,54,90,79.0,408,85,80.0,70,83,90,346,61,56,79.0,75,75.0,297,67,40.0,58,62,70,370,58,70.0,78.0,93.0,71,89.0,181,68,57,56.0,45,6,13,6,13,7,2014,420,58,70,85,85,63,59,149,170.18,68.04,4,4,4,0,2

In [37]:
## REPLACE ALL NANS TO 0

In [ ]:
for column in numericals.columns:
    sns.distplot(data[column])
    plt.show()

In [36]:
# Create a new dataframe with only the categorical columns using select_dtypes
categoricals = data_copy.select_dtypes(include = np.object)
categoricals.head()

,name,nationality,club,bp,position,foot,joined,contract,ls,st,rs,lw,lf,cf,rf,rw,lam,cam,ram,lm,lcm,cm,rcm,rm,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2,G. Pasquale,Italy,Udinese,LWB,LM,Left,"Jul 1, 2008",2008 ~ 2016,65+0,65+0,65+0,68+0,67+0,67+0,67+0,68+0,68+0,68+0,68+0,69+0,69+0,69+0,69+0,69+0,71+-2,70+-1,70+-1,70+-1,71+-2,70+-1,69+0,69+0,69+0,70+-1,17+0
16,Luis García,Spain,KAS Eupen,CM,CM CAM CDM,Right,"Jul 19, 2014",2014 ~ 2019,67+1,67+1,67+1,67+0,68+0,68+0,68+0,67+0,70+1,70+1,70+1,68+1,70+1,70+1,70+1,68+1,62+1,66+1,66+1,66+1,62+1,60+1,60+1,60+1,60+1,60+1,17+1
27,J. Cole,England,Coventry City,CAM,CAM RM RW LM,Right,"Jan 7, 2016",2016 ~ 2020,64+0,64+0,64+0,70+0,69+0,69+0,69+0,70+0,71+0,71+0,71+0,68+0,66+0,66+0,66+0,68+0,52+0,54+0,54+0,54+0,52+0,47+0,46+0,46+0,46+0,47+0,15+0
36,D. Yorke,Trinidad &amp; Tobago,Sunderland,ST,NaN,Right,NaN,2009,67+0,67+0,67+0,66+0,67+0,67+0,67+0,66+0,70+0,70+0,70+0,66+0,68+0,68+0,68+0,66+0,56+0,65+0,65+0,65+0,56+0,57+0,51+0,51+0,51+0,57+0,22+0
41,Iniesta,Spain,Vissel Kobe,CAM,CM CAM,Right,"Jul 16, 2018",2018 ~ 2021,72+3,72+3,72+3,79+0,79+0,79+0,79+0,79+0,82+-1,82+-1,82+-1,79+2,81+0,81+0,81+0,79+2,70+3,73+3,73+3,73+3,70+3,67+3,64+3,64+3,64+3,67+3,17+3

In [ ]:
for var in categoricals:
    counts = categoricals[var].value_counts()
    print("Counts for variable {}: \n{}".format(var, counts))

## 04 - Exploratory Data Analysis

In [ ]:
# Looking at promising talents

In [ ]:
data['pot_minus_ova'] = data['pot'] - data['ova']

In [ ]:
# Create a new DataFrame that contains only the rows with "difference" > 10 and age < 21
talents = data[(data['pot_minus_ova'] > 10) & (data['age'] < 21)]
talents.head()

In [ ]:
# Group the data by country and count the number of players in each country
talents_by_country = talents.groupby('nationality')['name'].count().sort_values(ascending=False)

# Plot a bar chart of the top 10 countries with the most players
talents_by_country.head(10).plot(kind='bar')

# Add labels and a title to the chart
plt.xlabel('Country')
plt.ylabel('Number of players')
plt.title('Top 10 countries with the most promising talents')

# Display the chart
plt.show()

In [ ]:
# Looking at MVPs with rating >80

In [ ]:
mvps = data[(data['ova'] > 80)]

In [ ]:
# Group the data by country and count the number of players in each country
mvps_by_country = mvps.groupby('nationality')['name'].count().sort_values(ascending=False)

# Plot a bar chart of the top 10 countries with the most players
mvps_by_country.head(10).plot(kind='bar')

# Add labels and a title to the chart
plt.xlabel('Country')
plt.ylabel('Number of players')
plt.title('Top 10 countries with the most valuable players')

# Display the chart
plt.show()

##### Check correlations

In [ ]:
round(data.corr(),2)

In [ ]:
#HEATMAP
mask = np.zeros_like(data.corr())
mask[np.triu_indices_from(mask)] = True # optional, to hide repeat half of the matrix
fig, ax = plt.subplots(figsize=(10, 8))
ax = sns.heatmap(data.corr(), mask=mask, annot=True)
plt.show()

# from this you can remove multicolinearity > 0.9 with no worry...
## ... > 0.75 is better to check with the model metrics to be sure
### when removing, keep the ones that have the highest correlation with target

In [ ]:
data.info()

## 05 - Processing Data

## 06 - Modeling

## 07 - Model Validation